image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/alaneaston/pottytracker
  tag: 'latest'

imageSelector:
  pullSecrets: []

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

env:
  DATABASE_URL: ""

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
