dropossNetwork:
  webPort: 31000
  hostNetwork: true

dropossConfig:
  username: admin
  password: admin

dropossStorage:
  data:
    type: pvc
  pgData:
    type: pvc
  pgBackup:
    type: emptyDir
    emptyDirConfig:
      medium: ""
      size: ""
