name: gitlab
description: GitLab Community Edition
annotations:
  title: GitLab
type: application
version: 1.0.0
apiVersion: v2
appVersion: latest
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://about.gitlab.com/
icon: https://about.gitlab.com/images/press/logo/png/gitlab-icon-rgb.png
sources:
  - https://about.gitlab.com/
  - https://github.com/truenas/charts/tree/master/community/gitlab
  - https://hub.docker.com/r/gitlab/gitlab-ce
keywords:
  - git
  - gitlab
