image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/alaneaston/pottytracker
  tag: 'latest'

imageSelector:
  pullSecrets: []

service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000

potty_db:
  host: ""
  port: 5432
  username: ""
  password: ""
  database: ""

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
