name: mailcow
description: Mailcow is an open source, modern email and groupware server suite.
annotations:
  title: Mailcow
type: application
version: 1.0.0
apiVersion: v2
appVersion: "2.35"
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common
    version: 1.2.9
home: https://mailcow.email/
icon: https://raw.githubusercontent.com/mailcow/mailcow-dockerized/master/data/web/img/cow_mailcow.svg
sources:
  - https://mailcow.email/
  - https://github.com/mailcow/mailcow-dockerized
  - https://github.com/truenas/charts/tree/master/community/mailcow
keywords:
  - mail
  - email
  - groupware
  - mailserver
  - sogo
  - dovecot
  - postfix
